djp_deployments:
    resource: "@DJPDeploymentsBundle/Resources/config/routing.yml"
    type:     rest
    prefix:   /api/

djp_user_management:
    resource: "@DJPUserManagementBundle/Resources/config/routing.yml"
    prefix:   /users/

djp_release_manager:
    resource: "@DJPReleaseManagerBundle/Controller"
    prefix:   /
    type:     annotation

dokapi:
    prefix:   /dokapi
    resource: "@DokapiSwaggerBundle/Resources/config/routing.yml"