djp_deployments:
    resource: "@DJPDeploymentsBundle/Controller"
    prefix:   /deployments/
    type:     annotation

djp_user_management:
    resource: "@DJPUserManagementBundle/Resources/config/routing.yml"
    prefix:   /users/

djp_release_manager_service:
    resource: "@DJPReleaseManagerServiceBundle/Resources/config/routing.yml"
    prefix:   /releases/

djp_release_manager:
    resource: "@DJPReleaseManagerBundle/Controller"
    prefix:   /
    type:     annotation

