<?php

namespace DJP\DeploymentsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DeploymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeploymentRepository extends EntityRepository
{
}
